# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('organization_type', models.CharField(db_index=True, max_length=50, verbose_name='Вид организации')),
                ('nalog_system', models.CharField(db_index=True, max_length=200, verbose_name='Система налогооблажения')),
                ('unp', models.PositiveIntegerField(default=1, verbose_name='УНП')),
                ('bank_schet', models.CharField(db_index=True, max_length=100, verbose_name='Банковский счет')),
                ('bank_BIK', models.CharField(db_index=True, max_length=100, verbose_name='IBAN')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Е-mail')),
                ('skype', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Скайп')),
                ('phone', models.PositiveIntegerField(blank=True, default=1, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contragent_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='ID Contragent')),
            ],
        ),
    ]
