# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171012_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='contragent_identy',
            name='end_date',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='contragent_identy',
            name='start_date',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='start_date'),
        ),
    ]
