# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-16 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hvosty_borders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hvosty_borders',
            old_name='docunent_end_data',
            new_name='document_end_data',
        ),
        migrations.RenameField(
            model_name='hvosty_borders',
            old_name='docunent_start_data',
            new_name='document_start_data',
        ),
    ]
