# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171030_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='contragent_identy',
            name='title',
        ),
        migrations.AlterField(
            model_name='client',
            name='nalog_system',
            field=models.CharField(blank=True, choices=[('УСН', 'усн.'), ('НДС', 'ндс.')], db_index=True, max_length=3, verbose_name='Система налогооблажения'),
        ),
    ]
