# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171103_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent_identy',
            name='start_date',
            field=models.DateField(),
        ),
    ]
