# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171115_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent_identy',
            name='start_date',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='по'),
        ),
    ]
