# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171118_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contragent_identy',
        ),
    ]
