# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('post_text', models.TextField(blank=True, verbose_name='текст')),
                ('post_image', models.ImageField(blank=True, upload_to='static/media/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name_plural': 'посты',
                'ordering': ['post_name'],
                'verbose_name': 'пост',
            },
        ),
    ]
