# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='mail_text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
    ]
