# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20170329_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='products/', verbose_name='Иконка')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('bank_schet', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('spheres', models.CharField(db_index=True, max_length=400, verbose_name='Тема')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Е-mail')),
                ('skype', models.CharField(db_index=True, max_length=200, verbose_name='Тема')),
                ('telegram', models.CharField(db_index=True, max_length=200, verbose_name='Тема')),
                ('phone', models.PositiveIntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
    ]
