# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='individual_number',
            field=models.PositiveIntegerField(default=1, verbose_name='УНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_schet',
            field=models.PositiveIntegerField(default=1, verbose_name='Банковский счет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.PositiveIntegerField(default=1, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='skype',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Скайп'),
        ),
        migrations.AlterField(
            model_name='client',
            name='spheres',
            field=models.CharField(db_index=True, max_length=400, verbose_name='Области деятельности'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Телеграм'),
        ),
    ]
