# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20161212_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutName', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('aboutDescription', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceName', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('priceDescription', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.RenameField(
            model_name='servs',
            old_name='description',
            new_name='servDescription',
        ),
        migrations.AlterField(
            model_name='servs',
            name='servName',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название услуги'),
        ),
    ]
