# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20161212_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servs',
            new_name='Serv',
        ),
    ]
