# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20161212_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('contactDescription', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
