# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientMail', models.TextField(blank=True, verbose_name='Почта')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
