# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20161213_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='clientMail',
        ),
        migrations.AddField(
            model_name='feedback',
            name='aboutName',
            field=models.CharField(db_index=True, default=' ', max_length=200, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='client',
            field=models.TextField(blank=True, default=' ', verbose_name='Почта'),
        ),
    ]
