# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20161213_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Как к вам обратиться?')),
                ('time', models.CharField(max_length=250, null=True, verbose_name='В какое время доставить товар?')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес доставки')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
