# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20161213_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Как к вам обратиться?')),
                ('address', models.CharField(max_length=250, verbose_name='ваша почта')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
