# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20161218_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='имя контакта')),
                ('contactIcon', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение товара')),
            ],
        ),
    ]
