# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20170102_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contlist',
            name='contactIcon',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение товара'),
        ),
    ]
