# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20170102_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contlist',
            name='contactIcon',
            field=models.ImageField(blank=True, upload_to='static/media/', verbose_name='Изображение товара'),
        ),
    ]
