# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20170102_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='contlist',
            name='contactDesc',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Полное имя или номер'),
        ),
        migrations.AlterField(
            model_name='contlist',
            name='contact',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Способ связи'),
        ),
    ]
