# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20170102_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Имя клиента')),
                ('clientIcon', models.ImageField(blank=True, upload_to='static/media/', verbose_name='Логотип')),
            ],
        ),
        migrations.AlterField(
            model_name='contlist',
            name='contactIcon',
            field=models.ImageField(blank=True, upload_to='static/media/', verbose_name='Иконка'),
        ),
    ]
