# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20170103_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
