# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_remove_contlist_contactdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contlist',
            name='contact',
        ),
        migrations.AddField(
            model_name='contlist',
            name='contactDesc',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Полное имя или номер'),
        ),
    ]
