# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_auto_20170108_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='contlist',
            name='contact',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Способ связи'),
        ),
    ]
