# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_contlist_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contlist',
            name='contact',
        ),
    ]
