# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_remove_contlist_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serv',
            options={'ordering': ['servName'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'услуга'},
        ),
    ]
