# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20170203_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['priceName'], 'verbose_name': 'Цены', 'verbose_name_plural': 'Расценки'},
        ),
        migrations.AlterModelOptions(
            name='serv',
            options={'ordering': ['servName'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
    ]
