# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_delete_newmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serv',
            name='servDescription',
        ),
    ]
