# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0030_remove_serv_servdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Ваша почта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Ваше имя либо название организации'),
        ),
    ]
