# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_auto_20170330_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serv',
        ),
    ]
