# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('nalog_system', models.CharField(blank=True, choices=[('УСН', 'усн.'), ('НДС', 'ндс.')], db_index=True, max_length=3, verbose_name='Система налогооблажения')),
                ('base_nuame', models.CharField(db_index=True, max_length=20, verbose_name='Номер базы')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.AlterIndexTogether(
            name='client',
            index_together=set([('slug',)]),
        ),
    ]
