# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_state', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='base_nuame',
            new_name='base_name',
        ),
    ]
