# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_state', '0002_auto_20180426_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, choices=[('1', 'dipartD'), ('2', 'avangard')], db_index=True, max_length=350)),
                ('file_obj', models.FileField(upload_to='docs/')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='file_obj',
            field=models.FileField(blank=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nalog_system',
            field=models.CharField(blank=True, choices=[('usn', 'usn'), ('nds', 'nds')], db_index=True, max_length=3, verbose_name='Система налогооблажения'),
        ),
    ]
