# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_state', '0004_remove_client_file_obj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
