# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_state', '0005_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='docs/')),
                ('start_year', models.CharField(blank=True, choices=[('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015')], db_index=True, max_length=350)),
                ('start_month', models.CharField(blank=True, choices=[('01', 'январь'), ('02', 'февраль'), ('03', 'март'), ('04', 'апрель'), ('05', 'май'), ('06', 'июнь'), ('07', 'июль'), ('08', 'август'), ('09', 'сентябрь'), ('10', 'октябрь'), ('11', 'ноябрь'), ('12', 'декабрь')], db_index=True, max_length=350)),
                ('start_day', models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], db_index=True, max_length=350)),
                ('end_year', models.CharField(blank=True, choices=[('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015')], db_index=True, max_length=350)),
                ('end_month', models.CharField(blank=True, choices=[('01', 'январь'), ('02', 'февраль'), ('03', 'март'), ('04', 'апрель'), ('05', 'май'), ('06', 'июнь'), ('07', 'июль'), ('08', 'август'), ('09', 'сентябрь'), ('10', 'октябрь'), ('11', 'ноябрь'), ('12', 'декабрь')], db_index=True, max_length=350)),
                ('end_day', models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], db_index=True, max_length=350)),
            ],
        ),
    ]
