# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 08:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_state', '0007_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='uploaded_file',
            field=models.FileField(upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
    ]
