# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singles', '0002_article_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_obj',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
