# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singles', '0003_auto_20180411_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='company_name',
            field=models.CharField(blank=True, choices=[('avangard', 'avangard')], db_index=True, max_length=350),
        ),
    ]
